services:
  app:
    build: .
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=test
      - CGO_ENABLED=1
    # No bind mount in CI to ensure clean environment
